### ISSUE TITLE
Updates for Alfred Gallery

### ISSUE THREAD

**Issue by vitorgalvao** [tru2dagame/alfred-switch-chrome-profiles#3]
@tru2dagame You’re more active on GitHub than the forum, so it may be more convenient to you to [point this out](https://www.alfredforum.com/topic/19103-alfred-switch-chrome-profiles/#comment-102696) here.

This is pretty much ready to go in the Gallery, but I’ve noticed a few things. Please see the linked forum post, but feel free to reply in this issue if you prefer.

**Comment by tru2dagame** [comment]
@vitorgalvao 

> OneUpdater has to be removed.

Sure. It is so nice that gallery workflows are updatable from within Alfred itself now.

> since Alfred 5 includes the Homebrew installation paths and users can [install dependencies directly from the Preferences](https://www.alfredapp.com/help/kb/dependencies/), the TOOLS_PATH config should also be removed.

Yes, please. I noticed this too.

> I want to ask what’s the jq branch of the Conditional is for. Does it serve a purpose or is it forgotten from a previous version?

Sorry for the confusion. No, I think it could be removed.

> I noticed the workflow’s name is set as Switch Chrome Profiles fzf. The fzf does not seem intentional.

FZF is what I use to filter the search result. I think the original title is `Switch Chrome Profiles w/ fzf`. But somehow I deleted the 'w/' and I can't remember why.
Maybe we could change the title to `Switch Chrome Profiles with FZF`

Additional FZF notes:
For example, with fzf I can do fuzzy search with `!`. 

<img width="450" alt="image" src="https://user-images.githubusercontent.com/1673006/218872827-a8f7c014-449e-4072-a551-b50da5aafcee.png">

I have another unpolished workflow to filter Safari / Chrome tabs with FZF. It definitely improves search results. ( Plan to submit it as well after deleting all the comments and unused stuff. )

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1673006/218874654-a4fa712f-4d74-4a48-a105-910af1f5d4f4.png">

**Comment by vitorgalvao** [comment]
@tru2dagame Would you mind pinging me when the changes above are ready and released? That way I can add this right after.

Also, thumbs up on the Safari tab search. From the screenshot, I’d make two (maybe premature) notes/recommendations:

* The current icon is for an alias (note the small arrow) instead of the Safari icon.
* Probably not worth repeating `tab: ` in every subtitle, seeing as they only show the URL.

**Comment by vitorgalvao** [comment]
@tru2dagame Checking if there’s progress here or you have any blockers.

**Comment by vitorgalvao** [comment]
Closing for now. If you’re interested in resubmitting at a later date with the above changes, please let me know and we can work on it.
